import { dfdOf, dfdViews } from '../core/dfd'
import { childViewKind, estimateVolume, type Attribute, type Consistency, type CrudOperation, type DfdBoundary, type DfdFlow, type DfdGroup, type DfdNode, type DfdRole, type DiagramView, type Element, type EntityVolume, type ErdRelationship, type IntermediateKind, type Project, type Relationship, type ViewKind } from '../core/model'
import type { Finding } from '../core/validate'

export interface ToolHost {
  getProject: () => Project
  getCurrentViewId: () => string
  listViews: () => Array<{ id: string; kind: ViewKind; scopeId: string | null; name: string; isDefault: boolean }>
  openView: (viewId: string) => boolean
  openScope: (kind: ViewKind, scopeId: string | null) => string | undefined
  createElement: (input: { name: string; kind: Element['kind']; parentId?: string; description?: string; technology?: string; containerCategory?: Element['containerCategory']; applicationKind?: Element['applicationKind']; dataStoreKind?: Element['dataStoreKind']; classification?: Element['classification']; storageKind?: Element['storageKind']; passthrough?: boolean }) => Element | { error: string }
  updateElement: (id: string, patch: Partial<Element>) => Element | { error: string }
  deleteElements: (ids: string[]) => string[]
  createRelationship: (input: { sourceId: string; targetId: string; label: string; technology?: string; erd?: Partial<ErdRelationship> }) => Relationship | { error: string }
  addAttribute: (entityId: string, name: string, patch: Partial<Attribute>) => Attribute | { error: string }
  updateAttribute: (entityId: string, attributeId: string, patch: Partial<Attribute>) => Attribute | { error: string }
  deleteAttribute: (entityId: string, attributeId: string) => boolean
  updateRelationship: (id: string, patch: Partial<Relationship>) => Relationship | { error: string }
  deleteRelationship: (id: string) => boolean
  arrangeView: (viewId?: string) => boolean
  findings: () => Finding[]
  createDfd: (input: { scopeId?: string; useCase: string }) => DiagramView | { error: string }
  addDfdNode: (input: { viewId: string; elementId?: string; role?: DfdRole; name?: string; description?: string; intermediateKind?: IntermediateKind }) => DfdNode | { error: string }
  createDfdFlow: (input: { viewId: string; sourceNodeId: string; targetNodeId: string; label?: string; technology?: string; dataRefs?: string[]; operations?: CrudOperation[] }) => DfdFlow | { error: string }
  createBoundary: (input: { viewId: string; name: string; flowIds: string[]; consistency?: Consistency }) => DfdBoundary | { error: string }
  placeDfdNode: (input: { viewId: string; nodeId: string; kind: Element['kind']; parentId?: string }) => Element | { error: string }
  importLinks: (input: { viewId: string }) => { imported: number }
  linkProcesses: (input: { viewId: string; sourceNodeId: string; targetNodeId: string; kind?: IntermediateKind; name?: string }) => { node: DfdNode; group?: DfdGroup } | { error: string }
}

interface ToolDefinition {
  name: string
  title: string
  description: string
  inputSchema: unknown
  execute: (input: Record<string, unknown>) => unknown
}

type ModelContext = { registerTool: (tool: ToolDefinition, options?: { signal?: AbortSignal }) => Promise<void> | void }

function log(tool: string, action: string, payload: Record<string, unknown>) {
  console.log('[WebMCP edit]', { timestamp: new Date().toISOString(), source: 'WebMCP', tool, action, ...payload })
}

/** Registers the C4 tool surface on document.modelContext when the browser provides it. Edits apply directly. */
export function registerWebMcpTools(host: ToolHost, onReady: (ready: boolean) => void): () => void {
  const modelContext = (document as Document & { modelContext?: ModelContext }).modelContext
  if (!modelContext) { onReady(false); return () => {} }
  const controller = new AbortController()
  const str = { type: 'string' }
  const tools: ToolDefinition[] = [
    { name: 'get_project_summary', title: 'Get project summary', description: 'Project name, current view, and counts.', inputSchema: { type: 'object', properties: {}, additionalProperties: false },
      execute: () => { const project = host.getProject(); return { project: project.name, currentViewId: host.getCurrentViewId(), elements: Object.keys(project.elements).length, relationships: Object.keys(project.relationships).length, views: Object.keys(project.views).length } } },
    { name: 'list_views', title: 'List views', description: 'Every diagram view with kind, scope, and default flag.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, execute: () => host.listViews() },
    { name: 'get_view', title: 'Get view', description: 'Elements and relationships of one view, or the current view.', inputSchema: { type: 'object', properties: { viewId: str }, additionalProperties: false },
      execute: (input) => { const project = host.getProject(); const view = project.views[String(input.viewId ?? host.getCurrentViewId())]; if (!view) return { error: 'Unknown view' }; const scoped = Object.values(project.elements).filter((element) => (element.parentId ?? null) === view.scopeId && (!view.elementRefs.length || view.elementRefs.includes(element.id))); return { view: { id: view.id, kind: view.kind, scopeId: view.scopeId, name: view.name }, elements: scoped, relationships: Object.values(project.relationships).filter((relationship) => scoped.some((element) => element.id === relationship.sourceId || element.id === relationship.targetId)) } } },
    { name: 'list_elements', title: 'List elements', description: 'Every canonical element.', inputSchema: { type: 'object', properties: { kind: str }, additionalProperties: false }, execute: (input) => Object.values(host.getProject().elements).filter((element) => !input.kind || element.kind === input.kind) },
    { name: 'open_view', title: 'Open view', description: 'Show a view in the editor.', inputSchema: { type: 'object', properties: { viewId: str }, required: ['viewId'], additionalProperties: false }, execute: (input) => ({ ok: host.openView(String(input.viewId)) }) },
    { name: 'enter_scope', title: 'Enter scope', description: 'Open the default child view of a software system, application container, or database container (its ERD).', inputSchema: { type: 'object', properties: { elementId: str }, required: ['elementId'], additionalProperties: false },
      execute: (input) => { const element = host.getProject().elements[String(input.elementId)]; if (!element) return { error: 'Unknown element' }; const kind: ViewKind | undefined = childViewKind(element); if (!kind) return { error: 'Element has no child scope' }; const viewId = host.openScope(kind, element.id); return viewId ? { ok: true, viewId } : { error: 'Could not open scope' } } },
    { name: 'validate_project', title: 'Validate project', description: 'Integrity errors and check findings for the active profile.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, execute: () => host.findings() },
    { name: 'create_element', title: 'Create element', description: 'Create a canonical element; containers need a software system parent, components an application container parent, entities (tables) a database container parent, or an owner entity to create a dependent table (the dependent relationship is created too). A new entity gets a surrogate primary key.', inputSchema: { type: 'object', properties: { name: str, kind: { type: 'string', enum: ['person', 'softwareSystem', 'externalSystem', 'container', 'component', 'entity', 'topic', 'folder'] }, parentId: str, description: str, technology: str, passthrough: { type: 'boolean' }, containerCategory: { type: 'string', enum: ['application', 'dataStore'] }, applicationKind: { type: 'string', enum: ['webBrowser', 'mobileApp', 'desktopApp', 'server', 'worker', 'other'] }, dataStoreKind: { type: 'string', enum: ['database', 'databaseSchema', 'pubSub', 'queue', 'bucket', 'cache', 'fileShare', 'other'] }, classification: { type: 'string', enum: ['resource', 'event', 'summary', 'work', 'code'] }, storageKind: { type: 'string', enum: ['table', 'view', 'materialized_view'] } }, required: ['name', 'kind'], additionalProperties: false },
      execute: (input) => { const result = host.createElement(input as never); if (!('error' in result)) log('create_element', 'create', { elementId: result.id, elementKind: result.kind, changes: input }); return result } },
    { name: 'rename_element', title: 'Rename element', description: 'Rename one canonical element; every view resolves the new name.', inputSchema: { type: 'object', properties: { elementId: str, name: str }, required: ['elementId', 'name'], additionalProperties: false },
      execute: (input) => { const before = host.getProject().elements[String(input.elementId)]; const result = host.updateElement(String(input.elementId), { name: String(input.name) }); if (!('error' in result)) log('rename_element', 'rename', { elementId: result.id, elementKind: result.kind, changes: { name: { from: before?.name, to: result.name } } }); return result } },
    { name: 'update_element', title: 'Update element', description: 'Patch description, technology, container taxonomy, entity classification, or entity storage kind (table, view, materialized_view).', inputSchema: { type: 'object', properties: { elementId: str, description: str, technology: str, containerCategory: str, dataStoreKind: str, sqlDialect: str, classification: str, storageKind: str }, required: ['elementId'], additionalProperties: false },
      execute: (input) => { const { elementId, ...patch } = input; const result = host.updateElement(String(elementId), patch as Partial<Element>); if (!('error' in result)) log('update_element', 'update', { elementId: result.id, elementKind: result.kind, changes: patch }); return result } },
    { name: 'delete_element', title: 'Delete element', description: 'Delete an element and its descendants.', inputSchema: { type: 'object', properties: { elementId: str }, required: ['elementId'], additionalProperties: false },
      execute: (input) => { const ids = host.deleteElements([String(input.elementId)]); log('delete_element', 'delete', { elementId: input.elementId, changes: { deleted: ids } }); return { deleted: ids } } },
    { name: 'create_relationship', title: 'Create relationship', description: 'Connect two canonical elements. Between two entities of one data store the line is an ERD relationship: kind reference (source is the many side holding the key), inherit, or label, with UML multiplicity at each end.', inputSchema: { type: 'object', properties: { sourceId: str, targetId: str, label: str, technology: str, erd: { type: 'object', properties: { kind: { type: 'string', enum: ['reference', 'dependent', 'inherit', 'label'] }, sourceCardinality: { type: 'string', enum: ['1', '0..1', '*', '1..*'] }, targetCardinality: { type: 'string', enum: ['1', '0..1', '*', '1..*'] }, important: { type: 'boolean' } }, additionalProperties: false } }, required: ['sourceId', 'targetId', 'label'], additionalProperties: false },
      execute: (input) => { const result = host.createRelationship(input as never); if (!('error' in result)) log('create_relationship', 'create', { relationshipId: result.id, changes: input }); return result } },
    { name: 'update_relationship', title: 'Update relationship', description: 'Patch label, technology, description, or the ERD kind and multiplicity.', inputSchema: { type: 'object', properties: { relationshipId: str, label: str, technology: str, description: str, erd: { type: 'object', properties: { kind: { type: 'string', enum: ['reference', 'dependent', 'inherit', 'label'] }, sourceCardinality: str, targetCardinality: str, important: { type: 'boolean' } }, additionalProperties: false } }, required: ['relationshipId'], additionalProperties: false },
      execute: (input) => { const { relationshipId, ...patch } = input; const result = host.updateRelationship(String(relationshipId), patch as Partial<Relationship>); if (!('error' in result)) log('update_relationship', 'update', { relationshipId, changes: patch }); return result } },
    { name: 'delete_relationship', title: 'Delete relationship', description: 'Delete one relationship.', inputSchema: { type: 'object', properties: { relationshipId: str }, required: ['relationshipId'], additionalProperties: false },
      execute: (input) => { const ok = host.deleteRelationship(String(input.relationshipId)); if (ok) log('delete_relationship', 'delete', { relationshipId: input.relationshipId, changes: {} }); return { ok } } },
    { name: 'list_attributes', title: 'List attributes', description: 'Every field of one entity with its flags; only important fields draw on the ERD card.', inputSchema: { type: 'object', properties: { entityId: str }, required: ['entityId'], additionalProperties: false },
      execute: (input) => { const element = host.getProject().elements[String(input.entityId)]; if (element?.kind !== 'entity') return { error: 'Unknown entity' }; return element.attributes ?? [] } },
    { name: 'add_attribute', title: 'Add attribute', description: 'Add a field to an entity. Set important to show it on the ERD card; a primary key is important by default.', inputSchema: { type: 'object', properties: { entityId: str, name: str, description: str, important: { type: 'boolean' }, primaryKey: { type: 'boolean' }, required: { type: 'boolean' }, unique: { type: 'boolean' } }, required: ['entityId', 'name'], additionalProperties: false },
      execute: (input) => { const { entityId, name, ...patch } = input; const flags = patch as Partial<Attribute>; const result = host.addAttribute(String(entityId), String(name), { ...flags, ...(flags.primaryKey ? { important: flags.important ?? true } : {}) }); if (!('error' in result)) log('add_attribute', 'create', { elementId: entityId, attributeId: result.id, changes: input }); return result } },
    { name: 'update_attribute', title: 'Update attribute', description: 'Patch a field: name, description, important, primaryKey, required, unique.', inputSchema: { type: 'object', properties: { entityId: str, attributeId: str, name: str, description: str, important: { type: 'boolean' }, primaryKey: { type: 'boolean' }, required: { type: 'boolean' }, unique: { type: 'boolean' } }, required: ['entityId', 'attributeId'], additionalProperties: false },
      execute: (input) => { const { entityId, attributeId, ...patch } = input; const result = host.updateAttribute(String(entityId), String(attributeId), patch as Partial<Attribute>); if (!('error' in result)) log('update_attribute', 'update', { elementId: entityId, attributeId, changes: patch }); return result } },
    { name: 'delete_attribute', title: 'Delete attribute', description: 'Remove one field from an entity.', inputSchema: { type: 'object', properties: { entityId: str, attributeId: str }, required: ['entityId', 'attributeId'], additionalProperties: false },
      execute: (input) => { const ok = host.deleteAttribute(String(input.entityId), String(input.attributeId)); if (ok) log('delete_attribute', 'delete', { elementId: input.entityId, attributeId: input.attributeId, changes: {} }); return { ok } } },
    { name: 'set_entity_volume', title: 'Set entity volume', description: 'Record sizing assumptions on an entity: bytes per row, initial rows, rows added per period, refresh mode and frequency, retention months. Returns the estimate at the project horizon.', inputSchema: { type: 'object', properties: { entityId: str, recordBytes: { type: 'number' }, initialRows: { type: 'number' }, growthRows: { type: 'number' }, growthPeriod: { type: 'string', enum: ['day', 'week', 'month', 'year'] }, refreshMode: { type: 'string', enum: ['append', 'upsert', 'rebuild'] }, refreshEvery: { type: 'string', enum: ['hourly', 'daily', 'weekly', 'monthly', 'on_demand'] }, retentionMonths: { type: 'number' }, note: str }, required: ['entityId'], additionalProperties: false },
      execute: (input) => { const { entityId, ...volume } = input; const current = host.getProject().elements[String(entityId)]; if (current?.kind !== 'entity') return { error: 'Unknown entity' }; const merged = { ...current.volume, ...(volume as Partial<EntityVolume>) }; const result = host.updateElement(String(entityId), { volume: merged }); if ('error' in result) return result; log('set_entity_volume', 'update', { elementId: entityId, changes: volume }); return { volume: merged, estimate: estimateVolume(merged, host.getProject().settings.volumeHorizonMonths) } } },
    { name: 'arrange_view', title: 'Arrange view', description: 'Run the automatic left-to-right layout on a view.', inputSchema: { type: 'object', properties: { viewId: str }, additionalProperties: false }, execute: (input) => ({ ok: host.arrangeView(input.viewId ? String(input.viewId) : undefined) }) },
    { name: 'list_dfds', title: 'List DFDs', description: 'Every data flow diagram with kind, scope, use case, and its nodes, flows, and transaction boundaries.', inputSchema: { type: 'object', properties: { scopeId: str }, additionalProperties: false },
      execute: (input) => dfdViews(host.getProject(), input.scopeId === undefined ? undefined : String(input.scopeId) || null).map((view) => ({ id: view.id, kind: view.kind, scopeId: view.scopeId, useCase: view.useCase, name: view.name, ...dfdOf(view) })) },
    { name: 'create_dfd', title: 'Create DFD', description: 'Create a use-case DFD for a software system: its application containers are processes, data stores and tables are stores, people and other systems are external entities.', inputSchema: { type: 'object', properties: { scopeId: str, useCase: str }, required: ['scopeId', 'useCase'], additionalProperties: false },
      execute: (input) => { const result = host.createDfd(input as never); if (!('error' in result)) log('create_dfd', 'create', { viewId: result.id, changes: input }); return result } },
    { name: 'add_dfd_node', title: 'Add DFD node', description: 'Add a node to a DFD: pass elementId to project an existing element (its role derives from its position), or role and name for a free node that is placed into the model later.', inputSchema: { type: 'object', properties: { viewId: str, elementId: str, role: { type: 'string', enum: ['external_entity', 'process', 'data_store', 'intermediate_data'] }, name: str, description: str, intermediateKind: { type: 'string', enum: ['file', 'queue'] } }, required: ['viewId'], additionalProperties: false },
      execute: (input) => { const result = host.addDfdNode(input as never); if (!('error' in result)) log('add_dfd_node', 'create', { viewId: input.viewId, nodeId: result.id, changes: input }); return result } },
    { name: 'create_dfd_flow', title: 'Create DFD flow', description: 'Connect two DFD nodes. A flow joins a process with a data node or an external entity; operations (C, R, U, D) apply at a data store end; dataRefs are entity ids or free text.', inputSchema: { type: 'object', properties: { viewId: str, sourceNodeId: str, targetNodeId: str, label: str, technology: str, dataRefs: { type: 'array', items: str }, operations: { type: 'array', items: { type: 'string', enum: ['C', 'R', 'U', 'D'] } } }, required: ['viewId', 'sourceNodeId', 'targetNodeId'], additionalProperties: false },
      execute: (input) => { const result = host.createDfdFlow(input as never); if (!('error' in result)) log('create_dfd_flow', 'create', { viewId: input.viewId, flowId: result.id, changes: input }); return result } },
    { name: 'create_transaction_boundary', title: 'Create transaction boundary', description: 'Mark flows of one DFD that succeed or fail together as atomic or eventual.', inputSchema: { type: 'object', properties: { viewId: str, name: str, flowIds: { type: 'array', items: str }, consistency: { type: 'string', enum: ['atomic', 'eventual'] } }, required: ['viewId', 'name', 'flowIds'], additionalProperties: false },
      execute: (input) => { const result = host.createBoundary(input as never); if (!('error' in result)) log('create_transaction_boundary', 'create', { viewId: input.viewId, boundaryId: result.id, changes: input }); return result } },
    { name: 'link_dfd_processes', title: 'Link DFD processes', description: 'Join two processes into one logical process group and insert intermediate data between them: api_document (default), file, or queue.', inputSchema: { type: 'object', properties: { viewId: str, sourceNodeId: str, targetNodeId: str, kind: { type: 'string', enum: ['api_document', 'file', 'queue'] }, name: str }, required: ['viewId', 'sourceNodeId', 'targetNodeId'], additionalProperties: false },
      execute: (input) => { const result = host.linkProcesses(input as never); if (!('error' in result)) log('link_dfd_processes', 'create', { viewId: input.viewId, nodeId: result.node.id, groupId: result.group?.id, changes: input }); return result } },
    { name: 'import_c4_links', title: 'Import C4 links into DFD', description: 'Turn every stored 1:1 component relationship between nodes of the DFD into a process -> API document -> process hop.', inputSchema: { type: 'object', properties: { viewId: str }, required: ['viewId'], additionalProperties: false },
      execute: (input) => { const result = host.importLinks({ viewId: String(input.viewId) }); log('import_c4_links', 'create', { viewId: input.viewId, changes: result }); return result } },
    { name: 'place_dfd_node', title: 'Place DFD node', description: 'Create a model element from a free DFD node and bind the node to it: a container or component under parentId, a person or external system at the root, an entity in a database.', inputSchema: { type: 'object', properties: { viewId: str, nodeId: str, kind: { type: 'string', enum: ['person', 'softwareSystem', 'externalSystem', 'container', 'component', 'entity'] }, parentId: str }, required: ['viewId', 'nodeId', 'kind'], additionalProperties: false },
      execute: (input) => { const result = host.placeDfdNode(input as never); if (!('error' in result)) log('place_dfd_node', 'create', { viewId: input.viewId, nodeId: input.nodeId, elementId: result.id, changes: input }); return result } },
  ]
  Promise.all(tools.map((tool) => modelContext.registerTool(tool, { signal: controller.signal }))).then(() => onReady(true)).catch(() => onReady(false))
  return () => controller.abort()
}
