// Builds the single executable (requirement:bun-backend): the frontend in dist/ is embedded file by file, so the
// binary serves it without anything beside it. Run after npm run build.
import { existsSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

const root = join(import.meta.dir, '..')
const dist = join(root, 'dist')
if (!existsSync(join(dist, 'index.html'))) throw new Error('Build the frontend first: npm run build')

const files: string[] = []
const walk = (dir: string) => readdirSync(dir).forEach((name) => { const path = join(dir, name); if (statSync(path).isDirectory()) walk(path); else files.push(path) })
walk(dist)

const lines = ['// Generated by server/build.ts; do not edit.']
files.forEach((file, index) => lines.push(`import asset${index} from ${JSON.stringify(`../${relative(root, file)}`)} with { type: 'file' }`))
lines.push('export const ASSETS: Record<string, string> = {')
files.forEach((file, index) => lines.push(`  ${JSON.stringify(`/${relative(dist, file).split('\\').join('/')}`)}: asset${index},`))
lines.push('}', '')
writeFileSync(join(import.meta.dir, 'assets.generated.ts'), lines.join('\n'))

const outfile = join(root, 'release', process.platform === 'win32' ? 'c4sketch.exe' : 'c4sketch')
const result = Bun.spawnSync(['bun', 'build', '--compile', '--minify', join(import.meta.dir, 'compiled.ts'), '--outfile', outfile], { stdout: 'inherit', stderr: 'inherit' })
if (result.exitCode !== 0) process.exit(result.exitCode ?? 1)
console.log(`${files.length} frontend files embedded in ${relative(root, outfile)}`)
